workflows:
  android-workflow:
    name: Gaylerii Build V3
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - name: Extract project
        script: |
          ls -la
          find . -name "*.zip" 
          unzip *.zip

      - name: Fix font issue
        script: |
          find Gaylerii/app/src/main/res -name "*.xml" -exec perl -i -pe 's/android:fontFamily="@font\/nunito_bold"//g' {} \;
          echo '<?xml version="1.0" encoding="utf-8"?><font-family xmlns:android="http://schemas.android.com/apk/res/android"></font-family>' > Gaylerii/app/src/main/res/font/nunito_bold.xml

      - name: Build APK
        script: |
          cd Gaylerii
          gradle wrapper --gradle-version 8.2
          ./gradlew assembleDebug

    artifacts:
      - Gaylerii/app/build/outputs/apk/debug/app-debug.apk
